### PR TITLE
fixed task naming conflict

### PR DESCRIPTION
**Pull request by adam-adamaszek**
fixed gradle 3.0 standard lifecycle plugins task naming conflict.

### CODE REVIEW

**Comment by SlevinBE** [comment]
Thanks for the PR! I'll merge it as soon as I've got some time to verify it.

**Comment by adam-adamaszek** [comment]
in the meantime, feel free to use this:

https://bintray.com/cabecao1/generic/gradle-fx-1.3.3-patched-for-gradle-3.x/

**Comment by SlevinBE** [comment]
Merged. This fixed is currently available on our snapshot repository (https://oss.sonatype.org/content/repositories/snapshots) as version 1.4.0-SNAPSHOT

**Comment by markus-ebenhoeh-smartsparrow** [comment]
Do you have rough idea when this change would be released?

**Comment by SlevinBE** [comment]
I've just released GradleFx 1.4.0 which includes this fix. Sorry for the delay, last few months have been very busy.

**Comment by markus-ebenhoeh-smartsparrow** [comment]
Thank you, this is very much appreciated!

**Pull request merged**
