### PR TITLE
fix: under gradle 3.1, gradlefx throws 'ResolveContext' exception

### LINKED ISSUE #233: Confusing error stack when run test before compileFlex
gradelfx, version 1.3.3

Run gradle test right after gradle clean without run gradle compileFlex, very comfusing error stack:

...

Executing task ':flash/swfs:cloud.console:copytestresources' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
from \path.to.project\trunk\flash\swfs\cloud.console\src\test\resources to \path.to.project\trunk\flash\swfs\cloud.console\build\reports
:flash/swfs:cloud.console:copytestresources (Thread[main,5,main]) completed. Took 0.032 secs.
:flash/swfs:cloud.console:test (Thread[main,5,main]) started.
:flash/swfs:cloud.console:test
Executing task ':flash/swfs:cloud.console:test' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:flash/swfs:cloud.console:test FAILED
:flash/swfs:cloud.console:test (Thread[main,5,main]) completed. Took 0.25 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flash/swfs:cloud.console:test'.
> org/gradle/api/artifacts/ResolveContext

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':flash/swfs:cloud.console:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/artifacts/ResolveContext
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$Trait$Helper.validateFilesExist(LibraryOptionsInjector.groovy:76)
        at org.gradlefx.cli.instructions.flexsdk.FlexUnitAppInstructions.validateFilesExist(FlexUnitAppInstructions.groovy)
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$Trait$Helper.addLibraries(LibraryOptionsInjector.groovy:64)
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$Trait$Helper$addLibraries$0.call(Unknown Source)
        at org.gradlefx.cli.instructions.flexsdk.FlexUnitAppInstructions.addLibraries(FlexUnitAppInstructions.groovy)
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$addLibraries.call(Unknown Source)
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$Trait$Helper.addMergedLibraries(LibraryOptionsInjector.groovy:35)
        at org.gradlefx.cli.common.optioninjectors.LibraryOptionsInjector$Trait$Helper$addMergedLibraries$1.call(Unknown Source)
        at org.gradlefx.cli.instructions.flexsdk.FlexUnitAppInstructions.addMergedLibraries(FlexUnitAppInstructions.groovy)
        at org.gradlefx.cli.instructions.flexsdk.FlexUnitAppInstructions.configure(FlexUnitAppInstructions.groovy:31)
        at org.gradlefx.cli.instructions.CompilerInstructionsBuilder.buildInstructions(CompilerInstructionsBuilder.groovy:42)
        at org.gradlefx.cli.instructions.CompilerInstructionsBuilder$buildInstructions.call(Unknown Source)
        at org.gradlefx.tasks.Test.compileTestRunner(Test.groovy:80)
        at org.gradlefx.tasks.Test.runFlexUnit(Test.groovy:70)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.artifacts.ResolveContext
        ... 79 more

### PR DESCRIPTION
**Pull request by shawn11ZX**
fixed #233

### CODE REVIEW

**Comment by SlevinBE** [comment]
Thanks for the PR! I've redirected the PR to our 'develop' branch, which is used for development.

Seems like two tests are failing, can you have a look at them?
```
org.gradlefx.cli.common.optioninjectors.FlexFrameworkRslOptionsInjectorTest > calling addFrameworkRsls with an Adobe Flex SDK and useDebugRSLSwfs turned on should add framework rsls to compiler arguments FAILED
    groovy.lang.MissingMethodException at FlexFrameworkRslOptionsInjectorTest.groovy:32
org.gradlefx.cli.common.optioninjectors.FlexFrameworkRslOptionsInjectorTest > calling addFrameworkRsls with an Apache Flex SDK and useDebugRSLSwfs turned on should add framework rsls to compiler arguments FAILED
    groovy.lang.MissingMethodException at FlexFrameworkRslOptionsInjectorTest.groovy:53
```

**Comment by shawn11ZX** [comment]
Sorry, I'll fix it ASAP.

**Comment by shawn11ZX** [comment]
The test failure happened because I have changed the gradle version. Changing it back will fix it.

**Comment by SlevinBE** [comment]
thanks! 👍

**Pull request merged**
