### PR TITLE
DMG support for AIR SDK

### PR DESCRIPTION
**Pull request by zakhio**
Implemented SdkDMGUnpacker

Fix for #241

### CODE REVIEW

**Comment by SlevinBE** [comment]
Awesome, looks great! Thanks for the PR!

**Comment by shamruk** [comment]
👍

**Comment by shamruk** [comment]
Can I try a version with this fix without building gradlefx myself (still haven't tried to build it on my own)

**Comment by zakhio** [comment]
Sure

Add next line to `repositories` block
`maven { url "https://oss.sonatype.org/content/repositories/snapshots" }`

Then add `-SNAPSHOT` to the version, for example
`classpath group: 'org.gradlefx', name: 'gradlefx', version: '1.5.1-SNAPSHOT', changing: true`

**Comment by shamruk** [comment]
works great, thanks!

**Comment by shamruk** [comment]
It doesn't work with Adobe AIR 28 Beta, any simple solution?

> Could not resolve com.adobe:AdobeAIRSDK:28.0.
         > Could not parse Ivy file http://fpdownload.macromedia.com/pub/labs/flashruntimes/air/AIRSDK_Compiler.dmg

**Comment by shamruk** [comment]
Works great with release AIR 28

**Pull request merged**
